package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common_lib",
    srcs = ["lib.cc"],
    hdrs = ["lib.h"],
    deps = [
        "@third_party//common:common_lib",
    ],
)
